PL/PL/Controllers/DepartamentoController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PL.Controllers
{
    public class DepartamentoController : Controller
    {
        //
        // GET: /Departamento/
        public ActionResult GetAll()
        {
            ML.Departamento departamento = new ML.Departamento();
            ML.Result result = BL.Departamento.GetAll();
            departamento.Departamentos = result.Objects.ToList();
            return View(departamento);
        }
        [HttpPost]
        public ActionResult Importar(HttpPostedFileBase ImportarArchivo)
        {
            ML.Result result = new ML.Result();
            result.Objects = new List<object>();

            string Ruta = string.Empty;

            if (ImportarArchivo != null)
            {

                string line;
                bool PrimeraLinea = true;

                using (var reader = new StreamReader(ImportarArchivo.InputStream))
                {

                    while ((line = reader.ReadLine()) != null)
                    {
                        if (!PrimeraLinea)
                        {
                            var temp = line.Split('|');

                            ML.Departamento departamento = new ML.Departamento();

                            //departamento.DepartamentoID = Convert.ToInt16(temp[0]);
                            departamento.Descripcion = temp[0];
                            result.Objects.Add(departamento);

                            BL.Departamento.Add(departamento);

                        }
                        else
                        {
                            PrimeraLinea = false;
                        }

                    }
                }
            }
            return RedirectToAction("GetAll");
        }
        public ActionResult Delete(int DepartamentoID)
        {
            ML.Result result = BL.Departamento.Delete(DepartamentoID);
            return RedirectToAction("GetAll");
        }
	}
}

PL/PL/Views/Departamento/GetAll.cshtml
@model ML.Departamento
@{
    ViewBag.Title = "GetAll";
}

<div class="container">
    <div class="row">
        <div class="=row">
            <div class="col-md-12">
                <h2>Departamento</h2>
            </div>
        </div>
        <div class="form-group" align="right">
            @using (Html.BeginForm("Importar", "Departamento", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <input style="text-align:center" type="file" name="ImportarArchivo" />
                <br />
                <input type="submit" value="Importar" />

            }
        </div>
        <table class="table table-bordered table-responsive">
            <thead>
                <tr>
                    <td>Eliminar</td>
                    <td>IdDepartamento</td>
                    <td>Descripcion</td>
                </tr>
            </thead>
            <tbody>
                @foreach (ML.Departamento departamento in Model.Departamentos)
                {
                    <tr>
                        <td><a class="btn btn-danger glyphicon glyphicon-trash" href="@Url.Action("Delete", "Departamento", new { DepartamentoID = departamento.DepartamentoID })" onclick="return confirm('Estas seguro que deseas eliminar este registro?');"></a></td>
                        <td>@departamento.DepartamentoID</td>
                        <td>@departamento.Descripcion</td>

                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>